module.exports = [
    { code: "it-IT", name: "Italiano (Italia)" },
    { code: "en-US", name: "Inglese (Stati Uniti)" },
    { code: "en-GB", name: "Inglese (Regno Unito)" },
    { code: "es-ES", name: "Spagnolo (Spagna)" },
    { code: "es-MX", name: "Spagnolo (Messico)" },
    { code: "fr-FR", name: "Francese (Francia)" },
    { code: "de-DE", name: "Tedesco (Germania)" },
    { code: "pt-BR", name: "Portoghese (Brasile)" },
    { code: "pt-PT", name: "Portoghese (Portogallo)" },
    { code: "ru-RU", name: "Russo (Russia)" },
    { code: "zh-CN", name: "Cinese Semplificato" },
    { code: "zh-TW", name: "Cinese Tradizionale" },
    { code: "ja-JP", name: "Giapponese (Giappone)" },
    { code: "ko-KR", name: "Coreano (Corea del Sud)" },
    { code: "ar-SA", name: "Arabo (Arabia Saudita)" },
    { code: "hi-IN", name: "Hindi (India)" },
    { code: "tr-TR", name: "Turco (Turchia)" },
    { code: "nl-NL", name: "Olandese (Paesi Bassi)" },
    { code: "pl-PL", name: "Polacco (Polonia)" },
    { code: "sv-SE", name: "Svedese (Svezia)" },
    { code: "el-GR", name: "Greco (Grecia)" },
    { code: "da-DK", name: "Danese (Danimarca)" },
    { code: "fi-FI", name: "Finlandese (Finlandia)" },
    { code: "no-NO", name: "Norvegese (Norvegia)" },
    { code: "cs-CZ", name: "Ceco (Repubblica Ceca)" },
    { code: "hu-HU", name: "Ungherese (Ungheria)" },
    { code: "ro-RO", name: "Rumeno (Romania)" },
    { code: "th-TH", name: "Tailandese (Tailandia)" },
    { code: "vi-VN", name: "Vietnamita (Vietnam)" }
];